Skyscanner/slate

- source/includes/_getting_started.md
> Minor typo fix

- source/includes/_hotels.md
Documentation added for Bellboy, the new hotels service replacing the deprecated old one.
> New hotels documentation

- source/includes/_places.md
Documentation for the new hotels autosuggest API
> New hotels autosuggest documentation

- source/includes/_flights_live_prices.md
Sorry for the whitespace changes, must be my Atom editor
> Add includeCarriers and excludeCarriers fields to create session doc

- source/includes/_redirects.md
> Referral service: adding info about new optional params

- source/includes/_flights_live_prices.md
Improving warning formatting
Before:
After:
> Fix warning message styling

- source/includes/_redirects.md
> BTBS-3044: fix broken link in booking redirects section

- source/includes/_hotels.md
- source/includes/_places.md
Update to newer style of endpoints.
> update gateway endpoints

- source/includes/_flights_live_prices.md
> found broken link in the documentation, fixing it

- source/includes/_authentication.md
- source/includes/_autosuggest.md
> BTBS-3303 Update documentation for autosuggest

- source/includes/_flights_live_prices.md
> BTBS-3311: fix confusing text in documentation

- source/includes/_referrals.md
> [PV-1289] updated referral service docs to contain the API's public URL

- source/includes/_flights_live_prices.md
> Update the cabin class in Flights Live Prices

- source/includes/_authentication.md
- source/includes/_places.md
> BTBS-3303: adding information about token endpoint for autosuggest

- source/includes/_places.md
> RM-364 change language id from en to en-GB

- source/includes/_hotels.md
> hotel endpoint document update

- README.md
- source/includes/_referrals.md
Updates the documentation with the utm_term optional parameter.
> RM-428 updates referral service readme for utm parameter

- generate_referral_service_docs.sh
- source/includes/_hotels_dayView.md
- source/includes/_hotels_homeView.md
- source/index.html.md
* JSON Schemas are updated in referrals-api (https://github.skyscannertools.net/partnerinsights/referrals-api/pull/71)
* New markdown for hotels home view
* Comments in the shell script for documentation generation
> RM-488 Add Hotels Home View Documentation

- generate_referral_service_docs.sh
- source/includes/_flights_homeView.md
- source/index.html.md
New markdown for flights home view
> [RM-487] Add flights home view documentation

- source/includes/_hotels_dayView.md
> RM-486 Update documentation for hotels day-view schema

- generate_referral_service_docs.sh
- source/includes/_cars_carsHome.md
- source/includes/_flights_homeView.md
- source/index.html.md
RM-489 updates car hire home page referral docs
> RM-489 updates car hire home page referral docs

- generate_referral_service_docs.sh
- source/includes/_flights_airline.md
- source/index.html.md
> RM-492: add documentation for Flights Airline links in Referral API

- generate_referral_service_docs.sh
- source/includes/_hotels_hotelDetails.md
- source/includes/_referrals.md
- source/index.html.md
> update referrals api docs with hotel details page

- source/includes/_cars_carsHome.md
- source/includes/_cars_dayView.md
- source/includes/_flights_airline.md
- source/includes/_flights_browseView.md
- source/includes/_flights_calendarMonthView.md
- source/includes/_flights_cheapFlightsTo.md
- source/includes/_flights_dayView.md
- source/includes/_flights_homeView.md
- source/includes/_flights_multiCity.md
- source/includes/_referrals.md
* adding examples
* fixing anchors
* fix typo
> more small changes and adding examples

- source/includes/_cars_carsHome.md
- source/includes/_cars_dayView.md
- source/includes/_flights_airline.md
- source/includes/_flights_browseView.md
- source/includes/_flights_calendarMonthView.md
- source/includes/_flights_cheapFlightsTo.md
- source/includes/_flights_dayView.md
- source/includes/_flights_homeView.md
- source/includes/_flights_multiCity.md
- source/includes/_referrals.md
Updates referral docs regarding the proper use of culture settings in the requests.
> RM-759 RM-760 updates referral docs on culture settings

- .travis.yml
> [FIX] removed second ruby env for travis

- source/includes/_flights_live_prices.md
> Clarifications for flights booking details request

- source/includes/_car_hire.md
- source/includes/_places.md
> Clarifying the carhire pickup/dropoff place parameters

- source/includes/_flights_dayView.md
> [RM-1024] Added showDirectDays to flights dayview documentation

- source/includes/_car_hire.md
- source/includes/_flights_live_prices.md
> [RM-832] Consolidate business.skyscanner.net pages

- source/includes/_flights_live_prices.md
> Clarifying the duration filter

- source/includes/_flights_live_prices.md
> Make itineraries filter by inbound/outbound depart time inclusive

- source/index.html.md
> Move dot out of hyperlink

- source/index.html.md
> Fix broken links

- source/includes/HTTPS_migration_guide.md
- source/includes/_authentication.md
- source/includes/_autosuggest.md
- source/includes/_car_hire.md
- source/includes/_cars_carsHome.md
- source/includes/_cars_dayView.md
- source/includes/_flights_dayView.md
- source/includes/_flights_live_prices.md
- source/includes/_hotels.md
- source/includes/_localisation.md
- source/includes/_places.md
- source/includes/_redirects.md
- source/includes/_referrals.md
This fixes some obvious grammar issues
> Update documentation with some spelling fixes

- .github/workflows/build.yml
- .github/workflows/deploy.yml
We don't use `main` branch for this project yet 😢
> Deploy when code is merged to `master` branch

- README.md
- source/includes/_flights_browse_dates.md
- source/includes/_flights_browse_grid.md
- source/includes/_flights_browse_notes.md
- source/includes/_flights_browse_quotes.md
- source/includes/_flights_browse_routes.md
- source/index.html.md
This is a refresh of the Flights Browse docs. I'm intending on updating the origin/destination & inbound/outbound-date tables in a follow-up PR.
> Update b2b browse docs

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- Gemfile
- Gemfile.lock
- source/includes/_places.md
- Includes lat-long for id queries
- Includes optional query parameters to include/exclude airports/cities/countries
> Update b2b autosuggest documentation

- .dockerignore
To allow Docker containers to actually have the documentation
> Allow sources to be in the docker image

- source/includes/_flights_live_prices.md.erb
The page is soon to be decommissioned
> Remove fps test harness link

- source/includes/_referrals.md.erb
Add warning for migrating referrals documentation to our new documentation page in docusaurus
> [MGP-742] add warning for deprecating referrals page
